version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./.env:/app/.env
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=/app

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dbt_project:/app/dbt_project
      - ./.env:/app/.env
    depends_on:
      - postgres
    command: ["dbt", "run", "--project-dir", "/app/dbt_project"]

volumes:
  postgres_data:
