name: "medical_data_platform"
version: "1.0.0"
config-version: 2

profile: "medical_data_platform"

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  medical_data_platform:
    staging:
      schema: staging
      materialized: view
    marts:
      schema: marts
      materialized: table

vars:
  start_date: "2023-01-01"
  end_date: "2025-07-13"
